- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
    name: "{{hlprobe_service_name}}"

- name: restart hlprobe
  service:
    name: "{{hlprobe_service_name}}"
    state: restarted
    enabled: yes